// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imfxqgmkjpkrcjwqndxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZnhxZ21ranBrcmNqd3FuZHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MjY1NjQsImV4cCI6MjA1ODUwMjU2NH0.D15zLcykg8Y_3vxC9Ncojf1XAN6T7-moJy7iae0bd_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});